### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by hederson** [EternalQuasar0206/cli-dotnet#3]
When do you think to launch a Nuget package for it?

**Comment by scarletquasar** [comment]
It is a good idea, I was having some problems at the time that I made it, but now looks like viable

**Comment by hederson** [comment]
Could I help you with that?

**Comment by scarletquasar** [comment]
I've implemented some fixes in [MelonRuntime]() CLI.NET built in version, but did not made changes in the original repository. You could adapt that [commit](https://github.com/MelonRuntime/MelonRuntime/commit/ef888860420efd6092682c58a5d6cbbc052b0b02) to a Pull Request here.

Context: There was happening a bug with `ExecuteEnvironmentCommands` method, just breaking and needs to be remade to accept different commands separated by `&&`

After you (or me) doing that I will release a new stable version, then publish on Nuget

**Comment by scarletquasar** [comment]
Solved in #5 

Implemented [Nuget Package](https://www.nuget.org/packages/Cli.NET/2.1.0) starting in version 2.1.0
